# Generated by Django 4.2 on 2024-03-11 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicTacToeBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_00', models.CharField(choices=[('', 'Empty'), ('X', 'X'), ('O', 'O')], default='', max_length=1)),
                ('cell_01', models.CharField(choices=[('', 'Empty'), ('X', 'X'), ('O', 'O')], default='', max_length=1)),
                ('cell_02', models.CharField(choices=[('', 'Empty'), ('X', 'X'), ('O', 'O')], default='', max_length=1)),
                ('cell_10', models.CharField(choices=[('', 'Empty'), ('X', 'X'), ('O', 'O')], default='', max_length=1)),
                ('cell_11', models.CharField(choices=[('', 'Empty'), ('X', 'X'), ('O', 'O')], default='', max_length=1)),
                ('cell_12', models.CharField(choices=[('', 'Empty'), ('X', 'X'), ('O', 'O')], default='', max_length=1)),
                ('cell_20', models.CharField(choices=[('', 'Empty'), ('X', 'X'), ('O', 'O')], default='', max_length=1)),
                ('cell_21', models.CharField(choices=[('', 'Empty'), ('X', 'X'), ('O', 'O')], default='', max_length=1)),
                ('cell_22', models.CharField(choices=[('', 'Empty'), ('X', 'X'), ('O', 'O')], default='', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='borad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_board', to='game.tictactoeboard'),
        ),
    ]
