# Generated by Django 4.2 on 2024-03-11 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_tictactoeboard_cell_00_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='borad',
            new_name='board',
        ),
    ]
