# Generated by Django 4.2 on 2024-03-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_rename_borad_game_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='temporary',
            field=models.CharField(default='Shivam', max_length=50),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Completed', 'Completed'), ('Draw', 'Draw')], default='Inactive', max_length=10),
        ),
    ]
